version: "2"
services:
  backend-build:
    build: ./backend-build
    volumes:
      - war-output:/mnt/build-out

  backend:
    restart: always
    build: ./backend
    expose:
      - "8080"
    ports:
      - "80:8080"
    depends_on:
      - backend-build
    volumes:
      - war-output:/usr/local/tomcat/webapps
      - /mnt/honeycomb/Data/tamsat/:/usr/local/tamsat-data


volumes:
  war-output:
    driver: local
  data:
    driver: local

networks:
  default:
