version: "3"
services:
  backend-build:
    build: ./backend-build
    volumes:
      - war-output:/mnt/build-out

  backend:
    restart: always
    build: ./backend
    expose:
      - "8080"
    ports:
      - "80:8080"
    depends_on:
      - backend-build
    volumes:
      - war-output:/usr/local/tomcat/webapps
      - tomcat-config-volume:/usr/local/tomcat/conf
      - tamsat-config-volume:/usr/local/tamsat-subset
      - /mnt/honeycomb/Data/tamsat/:/usr/local/tamsat-data

volumes:
  war-output:
    driver: local
  tomcat-config-volume:
    driver: local
  tamsat-config-volume:
    driver: local

networks:
  default:
